/* Generated by FastNate EntityImporter for H2Dialect */

/* Data from ProductImportData */
INSERT INTO Product (id, name, number, price) VALUES (1, 'Seife', 13040, 5.5);
INSERT INTO Product (id, name, number, price) VALUES (2, 'Duschgel', 13041, 3.9900000000000002131628207280300557613372802734375);
INSERT INTO Product (id, name, number, price) VALUES (3, 'Handtuch', 13022, 15.5);
INSERT INTO Product (id, name, number, price) VALUES (4, 'Lippenstift', 13033, 6.5);
INSERT INTO Product (id, name, number, price) VALUES (5, 'Deo', 13044, 5.5);
INSERT INTO Product (id, name, number, price) VALUES (6, 'Kosmetikpinsel', 13045, 21.5);
INSERT INTO Product (id, name, number, price) VALUES (7, 'Lotion', 13046, 4.9900000000000002131628207280300557613372802734375);
INSERT INTO Product (id, name, number, price) VALUES (8, 'Creme', 13047, 3.089999999999999857891452847979962825775146484375);
